
[general]
	#Summon both Keyblade and Armor with Summon Keyblade key
	summonTogether = false

	[general.gui]
		#Toggle HUD visibility, weapon option will show only while holding a Keyblade or Organization weapon
		#Allowed Values: SHOW, HIDE, WEAPON
		showGuiToggle = "HIDE"
		#Drive Forms Visibility
		showDriveForms = true

		[general.gui.command_menu]
			#Command Menu Text X Offset
			#Range: -1000 ~ 1000
			cmTextXOffset = 0
			#Command Menu Header Text Visibility
			cmHeaderTextVisibility = true
			#Command Menu X Scale %
			#Range: -1000 ~ 1000
			cmXScale = 100
			#Command Menu X Pos
			#Range: -1000 ~ 1000
			cmXPos = 0
			#Command Menu Selected X Offset
			#Range: -1000 ~ 1000
			cmSelectedXOffset = 5
			#Command Menu Submenu X Offset %
			#Range: -1000 ~ 1000
			cmSubXOffset = 100

		[general.gui.hp_bar]
			#Health Bar X Pos
			#Range: -1000 ~ 1000
			hpXPos = 0
			#Health Bar Y Pos
			#Range: -1000 ~ 1000
			hpYPos = 0
			#Show Hearts
			hpShowHearts = true
			#Low HP Alarm Volume
			#Range: 0 ~ 10
			hpAlarmVolume = 10
			#Health Bar X Scale
			#Range: -1000 ~ 1000
			hpXScale = 100

		[general.gui.mp_bar]
			#Magic Bar X Pos
			#Range: -1000 ~ 1000
			mpXPos = 0
			#Magic Bar Y Pos
			#Range: -1000 ~ 1000
			mpYPos = 0
			#Magic Bar X Scale
			#Range: -1000 ~ 1000
			mpXScale = 100

		[general.gui.dp_bar]
			#Drive Bar X Pos
			#Range: -1000 ~ 1000
			dpXPos = 0
			#Drive Bar Y Pos
			#Range: -1000 ~ 1000
			dpYPos = 0
			#Drive Bar X Scale
			#Range: -1000 ~ 1000
			dpXScale = 100
			#Drive Bar Y Scale
			#Range: -1000 ~ 1000
			dpYScale = 100

		[general.gui.player_skin]
			#Player Skin X Pos
			#Range: -1000 ~ 1000
			playerSkinXPos = 0
			#Player Skin Y Pos
			#Range: -1000 ~ 1000
			playerSkinYPos = 0

		[general.gui.lock_on]
			#Lock On HP X Pos
			#Range: -1000 ~ 1000
			lockOnXPos = 0
			#Lock On HP Y Pos
			#Range: -1000 ~ 1000
			lockOnYPos = 0
			#Lock On HP Bar Scale
			#Range: -1000 ~ 1000
			lockOnHPScale = 70
			#Lock On Icon Scale
			#Range: -1000 ~ 1000
			lockOnIconScale = 75
			#Lock On Icon Rotation Speed
			#Range: -1000 ~ 1000
			lockOnIconRotation = 16
			#Lock On HP per bar
			#Range: 10 ~ 100
			lockOnHpPerBar = 40

		[general.gui.party]
			#Party HUD X Pos
			#Range: -1000 ~ 1000
			partyXPos = 0
			#Party HUD Y Pos
			#Range: -1000 ~ 1000
			partyYPos = 0
			#Party HUD Y Offset
			#Range: -1000 ~ 1000
			partyYOffset = 60

		[general.gui.focus]
			#Focus HUD X Pos
			#Range: -1000 ~ 1000
			focusXPos = 0
			#Focus HUD Y Pos
			#Range: -1000 ~ 1000
			focusYPos = 0
			#Focus Bar X Scale
			#Range: -1000 ~ 1000
			focusXScale = 100
			#Focus Bar Y Scale
			#Range: -1000 ~ 1000
			focusYScale = 100

